namespace Gearify.SharedKernel.Messaging;

/// <summary>
/// Wrapper for SQS queue messages with metadata for idempotency.
/// </summary>
public class QueueMessage<T>
{
    /// <summary>
    /// SQS Message ID (assigned by SQS, not unique across retries)
    /// </summary>
    public string MessageId { get; set; } = string.Empty;

    /// <summary>
    /// SQS receipt handle for message deletion
    /// </summary>
    public string ReceiptHandle { get; set; } = string.Empty;

    /// <summary>
    /// Unique event identifier from EventEnvelope (for idempotency).
    /// This ID is generated by the publisher and remains the same across retries.
    /// Use this for duplicate detection, not MessageId.
    /// </summary>
    public string EventId { get; set; } = string.Empty;

    /// <summary>
    /// The deserialized event message body
    /// </summary>
    public T Body { get; set; } = default!;
}
